### ISSUE TITLE
direwolf will not compile with gpsd 3.23.1

### ISSUE THREAD

**Issue by km4ack** [wb2osz/direwolf#357]
If gpsd 3.23.1 is installed on a raspberry pi, direwolf will not compile. I get the error:

dwgpsd.c:64:2: error: #error libgps API version might be incompatible.
 #error libgps API version might be incompatible.

Without gpsd 3.23.1 installed, direwolf builds as it should. These are the steps I am taking to build direwolf:
    sudo apt-get install -y libasound2-dev cmake libudev-dev
    git clone https://www.github.com/wb2osz/direwolf
    cd direwolf
    mkdir build && cd build
    cmake ..
    make -j 4
    sudo make install
    make install-conf

**Comment by wb2osz** [comment]
This has been fixed in the dev branch.

**Comment by yuvadm** [comment]
@wb2osz thanks for the fix, is `dev` stable enough to be used or should users wait for that patch to land in `master`?

**Comment by wb2osz** [comment]
The "dev" branch is stable and I don't know of any regressions.
Try using the "dev" branch.
